version: "3.8"

services:
  mongo:
    image: mongo:4.2
    restart: always
    volumes:
      - .volumes/mongo:/data/db
    env_file:
      - .env
    expose:
      - 27017

  app:
    image: docker.pkg.github.com/diraven/crabot/IMAGE_NAME:VERSION
    depends_on:
      - mongo
    restart: always
    env_file:
      - .env
