version: "3.8"

services:
  mongo:
    image: mongo:4.4
    restart: always
    volumes:
      - .volumes/mongo:/data/db
    env_file:
      - .env
    expose:
      - 27017

  app:
    image: ghcr.io/diraven/crabot:master
    depends_on:
      - mongo
    init: true
    restart: always
    env_file:
      - .env
