[tool.pytest.ini_options]
addopts = "--cov=. --cov-fail-under=80"

["coverage:report"]
skip_empty = true

[tool.coverage.run]
branch = true
omit = [".*", "devops/*"]

[tool.coverage.report]
show_missing = true
skip_covered = true

[tool.pylint.BASIC]
good-names = [
  "id",
  "pk",
  "df",
  "i",
  "j",
  "k",
]

[tool.pylint."MESSAGES CONTROL"]
disable = [
  "bad-whitespace",
  "import-self",
  "logging-fstring-interpolation",
  "missing-class-docstring",
  "missing-function-docstring",
  "missing-module-docstring",
]

[tool.pylint.FORMAT]
max-line-length = 88

[tool.pylint.MASTER]
init-hook="import sys; sys.path.append('.')"
load-plugins = [
  "pylint_pytest",
]

[tool.pylint.SIMILARITIES]
ignore-imports = true
