version: "3.8"

volumes:
  mongo:
  root:

services:
  mongo:
    image: mongo:4.2
    restart: always
    volumes:
      - mongo:/data/db
    env_file:
      - ../.env
    expose:
      - 27017

  mongoexpress:
    image: mongo-express
    restart: "no"
    ports:
      - 80:8081
    volumes:
      - mongo:/data/db

  app:
    build: ..
    restart: "no"
    volumes:
      - ..:/workspace/
      - root:/root/
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace/
    command: /bin/sh -c "while sleep 1000; do :; done"
    env_file: ../.env
