version: "3.8"

volumes:
  root:

services:
  app:
    build: ..
    restart: "no"
    init: true
    volumes:
      - ..:/app/
      - root:/root/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:5000"
    working_dir: /app/
    command: /bin/sh -c "while sleep 1000; do :; done"
    env_file: ../.env
