name: CI
on:
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CI Pipeline
        run: |
          cp example_.env .env
          docker-compose --file .devcontainer/docker-compose.yml build
          docker-compose --file .devcontainer/docker-compose.yml run app bash devops/ci.bash
