name: CI

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run CI pipeline
        run: docker-compose run app bash devops/ci.bash
